version: 2

jobs:
  build-all:

    # We use the machine executor, i.e. a VM, not a container
    machine: true

    steps:
      - checkout

      - run:
          name: Ensure we have a clean docker environment
          command: |
            docker images "fundocker/openshift*"
            test -z $(docker images -q fundocker/openshift*)

      - run:
          name: Build services images
          command: |
            for service in $(ls docker/images); do
              bin/build $service
            done

      - run:
          name: Check build images
          command: |
            docker images "fundocker/openshift*"
            for service in $(ls docker/images); do
              ! test -z $(docker images -q fundocker/openshift-${service})
              echo "Image for service ${service} exists"
            done

  publish:

    # We use the machine executor, i.e. a VM, not a container
    machine: true

    steps:
      - checkout

      # Login to DockerHub to Publish new images
      #
      # Nota bene: you'll need to define the following secrets environment vars
      # in CircleCI interface:
      #
      #   - DOCKER_USER
      #   - DOCKER_PASS
      - run:
          name: Login to DockerHub
          command: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

      # We only publish build images upon new git tags with the following
      # pattern: <image_name>[:<image_tag>], e.g. nginx or nginx:1.13
      - run:
          name: Build & publish new service release
          command: |
            bin/build ${CIRCLE_TAG}
            bin/publish ${CIRCLE_TAG}

  publish-all:

    # We use the machine executor, i.e. a VM, not a container
    machine: true

    steps:
      - checkout

      # Login to DockerHub to Publish new images
      #
      # Nota bene: you'll need to define the following secrets environment vars
      # in CircleCI interface:
      #
      #   - DOCKER_USER
      #   - DOCKER_PASS
      - run:
          name: Login to DockerHub
          command: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

      # We loop on all services to build an up-to-date image and publish it
      - run:
          name: Build & publish all services
          command: |
            for service in $(ls docker/images); do
              bin/build $service
              bin/publish $service
              echo "Image for service ${service} was published"
            done

workflows:
  version: 2

  openshift-docker:
    jobs:

      # We always build all services for CI
      - build-all:
          filters:
            tags:
              only: /.*/

      # We publish new images for each git tag respecting the following
      # pattern: <image_name>[:<image_tag>], e.g. nginx or nginx:1.13
      - publish:
          requires:
            - build-all
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^(?!all)([A-Za-z0-9]+)(?:\:([0-9.]+))?/

      # We publish all services for each tag respecting the following pattern:
      # all-<date>, e.g. all-20180420
      - publish-all:
          requires:
            - build-all
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^all-(\d{4})([01]+\d+)([0-3]+\d+)/
